import { supabase } from '../../supabaseClient';
import type { PhysioComplaint } from '../../types';

function client() { if (!supabase) throw new Error('Supabase client is not configured'); return supabase; }
const fromRow = (row: any): PhysioComplaint => ({ id: row.id, teamId: row.team_id, playerId: row.player_id, occurrenceDate: row.occurrence_date, context: row.context, trainingSessionId: row.training_session_id, matchId: row.match_id, complaintType: row.complaint_type, location: row.location || '', affectedSide: row.affected_side, leftActivity: Boolean(row.left_activity), durationBand: row.duration_band, outcome: row.outcome, resultingInjuryId: row.resulting_injury_id, notes: row.notes || '', createdAt: row.created_at, updatedAt: row.updated_at });
const toRow = (item: Partial<PhysioComplaint>) => ({ ...(item.teamId !== undefined && { team_id: item.teamId }), ...(item.playerId !== undefined && { player_id: item.playerId }), ...(item.occurrenceDate !== undefined && { occurrence_date: item.occurrenceDate }), ...(item.context !== undefined && { context: item.context }), ...(item.trainingSessionId !== undefined && { training_session_id: item.trainingSessionId }), ...(item.matchId !== undefined && { match_id: item.matchId }), ...(item.complaintType !== undefined && { complaint_type: item.complaintType }), ...(item.location !== undefined && { location: item.location }), ...(item.affectedSide !== undefined && { affected_side: item.affectedSide }), ...(item.leftActivity !== undefined && { left_activity: item.leftActivity }), ...(item.durationBand !== undefined && { duration_band: item.durationBand }), ...(item.outcome !== undefined && { outcome: item.outcome }), ...(item.resultingInjuryId !== undefined && { resulting_injury_id: item.resultingInjuryId }), ...(item.notes !== undefined && { notes: item.notes }) });
export async function listPhysioComplaints(teamId: string): Promise<PhysioComplaint[]> { const { data, error } = await client().from('physio_complaints').select('*').eq('team_id', teamId).order('occurrence_date', { ascending: false }); if (error) throw error; return (data || []).map(fromRow); }
export async function createPhysioComplaint(item: Omit<PhysioComplaint, 'id' | 'createdAt' | 'updatedAt'>): Promise<PhysioComplaint> { const { data, error } = await client().from('physio_complaints').insert(toRow(item)).select('*').single(); if (error) throw error; return fromRow(data); }
export async function updatePhysioComplaint(id: string, patch: Partial<PhysioComplaint>): Promise<PhysioComplaint> { const { data, error } = await client().from('physio_complaints').update(toRow(patch)).eq('id', id).select('*').single(); if (error) throw error; return fromRow(data); }
